### ISSUE TITLE
Can there be more then 1 active domain per site?

### ISSUE THREAD

**Issue by markoheijnen** [markoheijnen/wordpress-mu-domain-mapping#1]
Currently through the network settings page you can have more then 1.

**Comment by ethitter** [comment]
There can be only one primary, but you can assign many domains to a given site, either via network admin or the domains page within a given site. The non-primary domains simply redirect to the primary domain, maintaining the requested path. I use this on my personal site because I own a variety of different TLDs for _ethitter_, but use _ethitter.com_ as the primary domain; if someone visits _ethitter.net_, for example, they're automatically redirected.

**Comment by markoheijnen** [comment]
Okay so it's broken when you fill in new domains through the network settings page. When using the site settings page then it works like that.

Also quite interesting that it is called active in the database instead of primary.

**Comment by ethitter** [comment]
I'll admit I'd never tried adding another domain via the network settings page, but it works for me in v0.5.4.3.

**Comment by markoheijnen** [comment]
Me too but was checking on notices. So added multiple domains and since active is default checked I saw that 1 site had multiple primary domains. Will check the logic.

**Comment by ethitter** [comment]
Ah, I see. I didn't try that, because I was testing on my live site. :)
